//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public long Key { get; set; }
        public Nullable<long> Category { get; set; }
        public string Name_ja { get; set; }
        public string Name_en { get; set; }
        public string Name_fr { get; set; }
        public string Name_de { get; set; }
        public string Help_ja { get; set; }
        public string Help_en { get; set; }
        public string Help_fr { get; set; }
        public string Help_de { get; set; }
        public Nullable<long> Point { get; set; }
        public Nullable<long> Item { get; set; }
        public Nullable<long> Icon { get; set; }
        public Nullable<long> Title { get; set; }
        public Nullable<long> Priority { get; set; }
        public byte[] data { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
