//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNpcName
    {
        public long Key { get; set; }
        public string SGL_ja { get; set; }
        public string SGL_en { get; set; }
        public string SGL_fr { get; set; }
        public string SGL_de { get; set; }
        public string area { get; set; }
        public byte[] data { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
