//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNpcName_PlaceName
    {
        public long BNpcName_Key { get; set; }
        public long PlaceName_Key { get; set; }
        public long region { get; set; }
    }
}
