//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colosseum
    {
        public long Key { get; set; }
        public Nullable<long> WinExp { get; set; }
        public Nullable<long> WinPoint { get; set; }
        public Nullable<long> WinToken { get; set; }
        public Nullable<long> LosePoint { get; set; }
        public Nullable<long> LoseToken { get; set; }
    }
}
