//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCRank
    {
        public long Key { get; set; }
        public Nullable<long> CurrentPoint { get; set; }
        public Nullable<long> NextPoint { get; set; }
    }
}
