//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gathering
    {
        public long Key { get; set; }
        public Nullable<long> Item { get; set; }
        public Nullable<long> GatheringType { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> levelView { get; set; }
        public Nullable<long> levelDiff { get; set; }
        public Nullable<bool> is_hidden { get; set; }
        public byte[] data { get; set; }
        public Nullable<long> GatheringNotebookList { get; set; }
        public Nullable<long> GatheringItemNo { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
