//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstanceContent
    {
        public long Key { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<long> Sortkey { get; set; }
        public string Name_ja { get; set; }
        public string Name_en { get; set; }
        public string Name_fr { get; set; }
        public string Name_de { get; set; }
        public string Description_ja { get; set; }
        public string Description_en { get; set; }
        public string Description_fr { get; set; }
        public string Description_de { get; set; }
        public Nullable<long> LevelMin { get; set; }
        public Nullable<long> LevelMax { get; set; }
        public Nullable<long> Time { get; set; }
        public Nullable<bool> Halfway { get; set; }
        public Nullable<long> RandomContentType { get; set; }
        public Nullable<bool> Alliance { get; set; }
        public Nullable<long> FinderPartyCondition { get; set; }
        public Nullable<long> PartyMemberCount { get; set; }
        public Nullable<long> TankCount { get; set; }
        public Nullable<long> HealerCount { get; set; }
        public Nullable<long> AttackerCount { get; set; }
        public Nullable<long> RangeCount { get; set; }
        public Nullable<bool> DifferentiateDPS { get; set; }
        public Nullable<long> PartyCount { get; set; }
        public Nullable<bool> FreeRole { get; set; }
        public Nullable<long> ItemLevel { get; set; }
        public Nullable<long> ItemLevelMax { get; set; }
        public Nullable<long> Colosseum { get; set; }
        public Nullable<long> Area { get; set; }
        public Nullable<long> ForceCount { get; set; }
        public byte[] data { get; set; }
        public string path { get; set; }
        public Nullable<bool> is_koeru_usually { get; set; }
        public Nullable<bool> is_koeru_annihilation { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
