//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Key { get; set; }
        public Nullable<long> Category { get; set; }
        public Nullable<long> UICategory { get; set; }
        public string UIName_ja { get; set; }
        public string UIName_en { get; set; }
        public string UIName_fr { get; set; }
        public string UIName_de { get; set; }
        public string Help_ja { get; set; }
        public string Help_en { get; set; }
        public string Help_fr { get; set; }
        public string Help_de { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> EquipLevel { get; set; }
        public Nullable<long> Rarity { get; set; }
        public Nullable<bool> HQ { get; set; }
        public Nullable<long> SpecialBonus { get; set; }
        public Nullable<long> Series { get; set; }
        public Nullable<long> Slot { get; set; }
        public Nullable<long> Damage { get; set; }
        public Nullable<long> Damage_hq { get; set; }
        public Nullable<long> MagicDamage { get; set; }
        public Nullable<long> MagicDamage_hq { get; set; }
        public Nullable<long> Defense { get; set; }
        public Nullable<long> Defense_hq { get; set; }
        public Nullable<long> MagicDefense { get; set; }
        public Nullable<long> MagicDefense_hq { get; set; }
        public Nullable<long> ShieldRate { get; set; }
        public Nullable<long> ShieldRate_hq { get; set; }
        public Nullable<long> ShieldBlockRate { get; set; }
        public Nullable<long> ShieldBlockRate_hq { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<long> PriceMin { get; set; }
        public Nullable<long> MirageItem { get; set; }
        public string icon { get; set; }
        public string icon_hq { get; set; }
        public string classjob { get; set; }
        public Nullable<long> Salvage { get; set; }
        public byte[] data { get; set; }
        public Nullable<bool> legacy { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
        public Nullable<long> SortId { get; set; }
    }
}
