//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public long Key { get; set; }
        public Nullable<long> Genre { get; set; }
        public Nullable<long> Area { get; set; }
        public string Name_ja { get; set; }
        public string Name_en { get; set; }
        public string Name_fr { get; set; }
        public string Name_de { get; set; }
        public Nullable<long> CompanyPointType { get; set; }
        public Nullable<long> CompanyPointNum { get; set; }
        public Nullable<long> Gil { get; set; }
        public Nullable<long> Client { get; set; }
        public Nullable<long> ExpBonus { get; set; }
        public Nullable<long> Header { get; set; }
        public Nullable<long> ClassLevel { get; set; }
        public Nullable<long> ClassLevel2 { get; set; }
        public Nullable<long> ClassJob { get; set; }
        public Nullable<long> ClassJob2 { get; set; }
        public Nullable<long> QuestLevelOffset { get; set; }
        public Nullable<long> Sort { get; set; }
        public Nullable<long> BeastTribe { get; set; }
        public Nullable<long> BeastReputationValueNum { get; set; }
        public Nullable<long> WebType { get; set; }
        public byte[] data { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
