//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public long Key { get; set; }
        public Nullable<long> CanAutoCraft { get; set; }
        public Nullable<long> CanHq { get; set; }
        public Nullable<long> CraftItemId { get; set; }
        public Nullable<long> CraftNum { get; set; }
        public Nullable<long> CraftType { get; set; }
        public Nullable<long> Level { get; set; }
        public Nullable<long> levelView { get; set; }
        public Nullable<long> levelDiff { get; set; }
        public Nullable<long> Element { get; set; }
        public Nullable<long> NeedCraftmanship { get; set; }
        public Nullable<long> NeedControl { get; set; }
        public Nullable<long> Number { get; set; }
        public Nullable<long> NeedStatus { get; set; }
        public Nullable<long> NeedEquipItem { get; set; }
        public byte[] data { get; set; }
        public string path { get; set; }
        public string Index_ja { get; set; }
        public string Index_en { get; set; }
        public string Index_fr { get; set; }
        public string Index_de { get; set; }
    }
}
