//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaintCoinach.Libra
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public long Key { get; set; }
        public string Female_de { get; set; }
        public string Female_en { get; set; }
        public string Female_fr { get; set; }
        public string Female_ja { get; set; }
        public Nullable<bool> Front_de { get; set; }
        public Nullable<bool> Front_en { get; set; }
        public Nullable<bool> Front_fr { get; set; }
        public Nullable<bool> Front_ja { get; set; }
        public string Male_de { get; set; }
        public string Male_en { get; set; }
        public string Male_fr { get; set; }
        public string Male_ja { get; set; }
    }
}
